package connection.constants;

public enum BuddylistErrorMode {
   YOUR_BUDDY_LIST_IS_FULL(0xB),
   OTHER_BUDDY_LIST_IS_FULL(0xC), // OTHER_BUDDY_LIST_IS_FULL
   ALREADY_REGISTERED_AS_FRIEND(0xD), // ALREADY_REGISTERED_AS_FRIEND
   GM_CANNOT_BE_BEFRIENDED(0xE), // GM_CANNOT_BE_BEFRIENDED
   CHARACTER_NOT_FOUND(0xF), // CHARACTER_NOT_FOUND
   UNABLE_TO_PROCESS_FOR_UNKNOWN_REASON(0x10), // UNABLE_TO_PROCESS_FOR_UNKNOWN_REASON
   UNABLE_TO_PROCESS_FOR_UNKNOWN_REASON_2(0x11), // UNABLE_TO_PROCESS_FOR_UNKNOWN_REASON_2
   UNABLE_TO_PROCESS_FOR_UNKNOWN_REASON_3(0x13), // UNABLE_TO_PROCESS_FOR_UNKNOWN_REASON_3
   UNABLE_TO_PROCESS_FOR_UNKNOWN_REASON_4(0x16); // UNABLE_TO_PROCESS_FOR_UNKNOWN_REASON_4

   final byte mode;

   BuddylistErrorMode(int mode) {
      this.mode = (byte) mode;
   }

   public byte getMode() {
      return mode;
   }
}