package connection.constants;

public enum CashShopOperationClientMode {
    LIMIT_GOODS_COUNT_CHANGED(0x4A),
    LOAD_LOCKER_DONE(0x4E),
    LOAD_LOCKER_FAILED(0x4F),
    LOAD_GIFT_DONE(0x50),
    LOAD_GIFT_FAILED(0x51),
    LOAD_WISH_DONE(0x52),
    LOAD_WISH_FAILED(0x53),
    SET_WISH_DONE(0x56),
    SET_WISH_FAILED(0x57),
    BUY_DONE(0x58),
    BUY_FAILED(0x59),
    USE_COUPON_DONE(0x5A),
    GIFT_COUPON_DONE(0x5C),
    INCREASE_SLOT_COUNT_DONE(0x61),
    INCREASE_SLOT_COUNT_FAILED(0x62),
    INCREASE_TRUNK_COUNT_DONE(0x63),
    INCREASE_TRUNK_COUNT_FAILED(0x64),
    INCREASE_CHARACTER_SLOT_COUNT_DONE(0x65),
    INCREASE_CHARACTER_SLOT_COUNT_FAILED(0x66),
    INCREASE_BUY_CHARACTER_COUNT_DONE(0x67),
    INCREASE_BUY_CHARACTER_COUNT_FAILED(0x68),
    ENABLE_EQUIP_SLOT_EXT_DONE(0x69),
    ENABLE_EQUIP_SLOT_EXT_FAILED(0x6A),
    MOVE_L_TO_S_DONE(0x6B),
    MOVE_L_TO_S_FAILED(0x6C),
    MOVE_S_TO_L_DONE(0x6D),
    MOVE_S_TO_L_FAILED(0x6E),
    DESTROY_DONE(0x6F),
    DESTROY_FAILED(0x70),
    EXPIRE_DONE(0x71),
    REBATE_DONE(0x88),
    REBATE_FAILED(0x89),
    COUPLE_DONE(0x8A),
    COUPLE_FAILED(0x8B),
    BUY_PACKAGE_DONE(0x8C),
    BUY_PACKAGE_FAILED(0x8D),
    GIFT_PACKAGE_DONE(0x8E),
    GIFT_PACKAGE_FAILED(0x8F),
    BUY_NORMAL_DONE(0x90),
    BUY_NORMAL_FAILED(0x91),
    FRIENDSHIP_DONE(0x94),
    FRIENDSHIP_FAILED(0x95),
    PURCHASE_RECORD(0x9D),
    FREE_CASH_ITEM_DONE(0xA1),
    NAME_CHANGE_BUY_DONE(0xA5),
    TRANSFER_WORLD_DONE(0xAE),
    TRANSFER_WORLD_FAILED(0xAF);


    final byte mode;

    CashShopOperationClientMode(int code) {
        this.mode = (byte) code;
    }

    public byte getMode() {
        return mode;
    }
}
